### ISSUE TITLE
deploying live on ec2: handling video streaming port 8081

### ISSUE THREAD

**Issue by stanchiang** [phoboslab/jsmpeg#147]
i got the demo to work on localhost, but would like to take it a step further and deploy it to a standard ec2 instance. installing was simple, but i'm a networking noob so i'm not familiar with managing ports. using http://www.lauradhamilton.com/how-to-set-up-a-nodejs-web-server-on-amazon-ec2 i got the page to load. 

However, the video stream on port 8081 still needs handling. but i have no idea what needs to be done. 

Does anyone know what i need to do to push the video stream to the player correctly?

i also posted the question to stackoverflow:
http://stackoverflow.com/questions/42891794/handling-multiple-ports-for-video-streaming-via-jsmpeg-on-ec2

ps: thanks for sharing such an intriguing project!

**Comment by phoboslab** [comment]
I'm not sure what the problem is, but the article seems to over-complicate things quite a bit. It's perfectly fine to allow access on port 80. No port forwarding needed. So you'll have to allow connections to your EC2 host on port 80 (for the web server), 8081 (for the incoming video stream) and 8082 (for the outgoing WebSocket connections).

Just start your Web Server on port 80: `http-server -p 80`.
Then start the websocket-relay: `node websocket-relay yoursecret 8081 8082`

Then send your video stream to your EC2 host on port 8081 and you should be able to see it in a browser.
