### ISSUE TITLE
freeze every few seconds

### ISSUE THREAD

**Issue by ViezeVingertjes** [phoboslab/jsmpeg#190]
Hi,

I am currently using Jsmpeg and i notice every few seconds it will freeze for probably about half a second., run choppy a few frames and then continue until it happens again.

Anyone that experiences the same issue? (live streaming of a camera, no static files)
It's the same with the ffmpeg (RPI) example provided on this repository page.

**Comment by physiii** [comment]
What's your connection?

**Comment by ViezeVingertjes** [comment]
Sufficient i would say, 130Mbps/30Mbps. But it does not seem to have to do with connection speed, as it's on the lowest resolution, quality and it's also the case on the internal network. Can't find the exact cause, so if it's only me, then it can be closed.

**Comment by Lizhooh** [comment]
+ 1, I think this is the server bandwidth problem

**Comment by milankragujevic** [comment]
I disagree, on localhost on a powerful CPU it stutters horrendously.

**Comment by ViezeVingertjes** [comment]
Yes, i had the same on the local network. Very small resolution, low framerate etc. so it cant be a bandwidth issue. I went for a FPV solution in the end for my project, that solved it for me. (lookup wifibroadcast)

**Comment by ahmethakanbillur** [comment]
I have same problem and I know solution path but I cant apply this because of as following;
Firstly, You should have idea about multiplexer in ffmpeg and you have 2 way for solution.You should set to mux parameter to vlc or ffmpeg.For this, I applied to use ffmpeg-fluent for accessing to ffmpeg's command but didnt work because of that I didnt see func in ffmpeg-fluent about setting mux parameter.
I will try to set mux parameter to vlc.
