### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by FengChueng** [phoboslab/jsmpeg#303]
there is no error When I use the command line.
eg: ffmpeg -i rtsp://admin:123456@192.168.1.151:554/h264/sub/av_stream -f mpegts -c:v mpeg1video -s 800x600 -r 30 -b:v 1000k -bf 0 http://192.168.1.190:8081/supersecret/test1

But when I use c# to call the API provided by ffmpeg, an exception is thrown.

crying for help!!!
thanks!

**Comment by BenNottelling** [comment]
Would probably be helpful to show your C# code

**Comment by FengChueng** [comment]
thanks for your reply。
Now，I solved the problem temporarily by changing the property videoBufferSize of player from 1024*1024*4  to 1024*1024*8;
new JSMpeg.Player(url, {canvas: canvas,videoBufferSize: 1024*1024*8});
[https://github.com/phoboslab/jsmpeg/issues/268](url)

**Comment by iairsalem** [comment]
Clarification, for future newcommers: when @FengChueng said:
> 102410248
he was probably referring to:
`new JSMpeg.Player(url, {canvas: canvas, videoBufferSize: 1024*1024*8})` instead of 1024*1024*4.
This is to say that instead of 4 MiB, he wanted the cache to be 8MiB (which is pretty similar to an uncompressed 4K video frame). (source:
https://www.videoproc.com/edit-4k-video/video-size-calculator.htm#:~:text=Like%20we%20have%20said%2C%20we,2160%20x%208%20%3D%2070778880%20bits.)

I came to revisit this issue because in the beginning I fixed it by putting: 102410248 which now I see is more than 100mb buffer per player (which is a lot)
So, again, probably correct approach would be: videoBufferSize:1024*1024*8 (you can stretch it to 10 instead of 8).

Let me know!
