### ISSUE TITLE
Get video duration

### ISSUE THREAD

**Issue by ShimaMax** [phoboslab/jsmpeg#311]
How to get video duration? I use "progressive: false" option, maybe it can be calculated using frame rate, resolution and size? Because I can't find anything like as "duration" field.

**Comment by phoboslab** [comment]
This is not implemented.

You can count the frames by calling `this.bits.findStartCode(MPEG1.START.PICTURE)` until it returns `-1` and rewind the buffer afterwards. You should do this after demuxing. E.g. in [MPEG1.prototype.write](https://github.com/phoboslab/jsmpeg/blob/master/src/mpeg1.js#L29).

It gets a bit more complicated when WASM is enabled, as the WASM version writes directly into the heap, instead of keeping its own buffer. See [mpeg1-wasm.js](https://github.com/phoboslab/jsmpeg/blob/master/src/mpeg1-wasm.js#L72).

As you already figured out, this only works with `progressive: false`.

**Comment by phoboslab** [comment]
I'm an idiot.

`var duration = player.video.timestamps.length / player.video.frameRate;`

**Comment by ShimaMax** [comment]
Thanks a lot!)
