### ISSUE TITLE
Does work in iOS?

### ISSUE THREAD

**Issue by jbonor** [phoboslab/jsmpeg#41]
I have tried several demos on several iOS devices (iphone 5, ipad 1) tested on safari and chrome and in all cases the image does not show up. Only shows "loading..."
It's like the canvas does not get painted because I can see in my own server that the websockets are connecting fine and the video is streaming (at least for a while).

Any ideas?
TIA

**Comment by phoboslab** [comment]
Chrome for iOS is likely too slow to render jsmpeg video, because it can't use the JavaScript JIT. Likewise, I'm not sure if the iPad1 is fast enough.

What iOS version are you using? Some older versions don't support Typed Arrays, which jsmpeg needs. Which demos did you try? Is it only the live streaming that doesn't work? What about the preloaded video examples like this: http://phoboslab.org/files/jsmpeg/

**Comment by andyearnshaw** [comment]
> Chrome for iOS is likely too slow to render jsmpeg video, because it can't use the JavaScript JIT. Likewise, I'm not sure if the iPad1 is fast enough.

iPad 1 is definitely not fast enough.  iOS 8's WebGL helps Chrome along with low res (~480p) videos, but not enough for full speed.  Aside from performance, I've had no problems testing across a wide range of mobile devices, but I don't use the web socket stuff.
