### ISSUE TITLE
Loading video stream via some event, NOT on page load doesn't work

### ISSUE THREAD

**Issue by becauseinterwebs** [phoboslab/jsmpeg#45]
I've been trying to have the video stream start only after a user clicks a button (or some other event), but I am finding that if jsmpeg is not invoked on page load, it won't start.

For example, you can do a simple test...this works fine (as in the example):

var player = new jsmpeg(client, {canvas:canvas});

But if you delay it in any way, like below.  It will not start.

var player;
setTimeout(function() {
  player = new jsmpeg(client, {canvas:canvas});
}, 1);

Is there a way to have it start on demand and NOT just when the page loads?

Thanks!

**Comment by phoboslab** [comment]
You should definitely be able to start jsmpeg in response to an event, like in the example you provided. 

There's probably something else going wrong. Are you sure `client` is a valid WebSocket instance? Also, it's important that the WebSocket is not yet connected when you hand it over to jsmpeg, because jsmpeg listens for the `onconnect` event. So you have to create the WebSocket instance just before creating the jsmpeg instance. Please provide a full example.

**Comment by becauseinterwebs** [comment]
Hi Dominic,

Yes my websocket is already instantiated...thank you I will try not
connecting until my event fires and let you know.

**Comment by becauseinterwebs** [comment]
Hi Dominic,

Yep, that was it :)  Thank you!
